{{- if eq (include "isProductionWithoutMasterKey" .) "true" }}
{{- $secretName := printf "%s-%s" (include "meilisearch.fullname" . ) "master-key" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  {{- if $secret }}
  MEILI_MASTER_KEY: {{ $secret.data.MEILI_MASTER_KEY }} 
  {{ else }}
  MEILI_MASTER_KEY: {{ randAlphaNum 20 | b64enc }}
  {{- end }}
{{ end }}