apiVersion: v1
kind: Service
metadata:
  name: {{ include "meilisearch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "meilisearch.name" . }}
    helm.sh/chart: {{ include "meilisearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq "NodePort" .Values.service.type }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "meilisearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
