name: Manifest
on:
  pull_request:
    branches:
      - main

jobs:
  check-chart-manifest-in-sync:
    name: Check in sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check helm template in sync
        id: helm_template
        run: |
          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
          if git diff --quiet && git diff --quiet --cached; then 
            echo "✅ Manifests are in sync"; 
          else 
            echo "❌ Manifest update required. Run "helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml" in the repository and push it";
            exit 1
          fi
