name: Tests
on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: lint
          config: ct.yaml

  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.0.1
        with:
          command: install
          config: ct.yaml

  check-chart-manifest-in-sync:
    name: Check in sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check helm template in sync
        id: helm_template
        run: |
          helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml
          if git diff --quiet && git diff --quiet --cached; then 
            echo "✅ Manifests are in sync"; 
          else 
            echo "❌ Manifest update required. run "helm template meilisearch charts/meilisearch | grep -v 'helm.sh/chart:\|app.kubernetes.io/managed-by:' > manifests/meilisearch.yaml" in the repository and push it;
            exit 1
          fi
